version: '3.4'
services:
    nodejs-app:
        build:
          context: .
        container_name: nodechat
        hostname: nodechat
        ports:
            - "4000:4000" 
        networks:
            - example-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "4040:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
    external: true